AWSTemplateFormatVersion: "2010-09-09"
Description: vpc create template

Parameters:
  EnvironmentName:
    Type: String
    Default: test-environment
 
Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB ingress group
      GroupName: !Sub ${EnvironmentName}-alb-sg
      VpcId: !ImportValue test-environment-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-alb-sg

  TARGETGROUPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Target Group ingress group
      GroupName: !Sub ${EnvironmentName}-tg-sg
      VpcId: !ImportValue test-environment-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-tg-sg
