AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFront Stack

Parameters:
  DomainName:
    Type: String

  CertificateID:
    Type: String
    Default: "9835312c-daff-44a8-9f9c-314e09797ff5"
  
  BucketName:
    Type: String

Resources:

  OAC: 
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Access Control
        Name: OAC-20220102
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all
        Enabled: true
        Origins: 
          - DomainName: !Sub ${BucketName}.s3.ap-northeast-1.amazonaws.com
            Id: S3
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig: 
              OriginAccessIdentity: ''
        PriceClass: PriceClass_200
        DefaultRootObject: "index.html"
        Aliases:
          - !Sub "${DomainName}"
        ViewerCertificate:
          AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertificateID}"
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"

Outputs:
  CloudFrontID:
    Value: !Ref CloudFront
    Export: 
      Name: CloudFrontID-20230102