AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: S3 Configuration
        Parameters:
          - BucketName
          - FileName1
          - FileName2
#          - RestrictingIpAddress

Parameters:
  BucketName:
    Description: S3 bucket that's used for the website hosting
    Type: String
  FileName1:
    Type: String
    Description: FileName1 of the file name for restricting S3 bucket
  FileName2:
    Type: String
    Description: FileName2 of the file name for restricting S3 bucket
 # RestrictingIpAddress:
 #   Type: String
 #   Description: RestrictingIpAddress of the file name for restricting Ip address


Resources:
  IAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-user
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub "arn:aws:s3:::${BucketName}"
            Action:
              - s3:ListBucket
            Condition:
              IpAddress:
                aws:SourceIp: "11.22.33.44/32"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}/${FileName1}"
              - !Sub "arn:aws:s3:::${BucketName}/${FileName2}"
            Condition:
              IpAddress:
                aws:SourceIp: "11.22.33.44/32"

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${AWS::StackName}-user
      ManagedPolicyArns:
        - !Ref IAMPolicy

  IAMUser1AccessKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: !Ref IAMUser
        
Outputs:
  AccessKeyformyaccesskey:
    Value: !Ref IAMUser1AccessKey
  SecretKeyformyaccesskey:
    Value: !GetAtt IAMUser1AccessKey.SecretAccessKey